#!/bin/bash

# Programa al que se le pasa como parámetro una edad:
## - Si es mayor o igual a 18 años, escribe: "Es mayor de edad."
## - Si la edad es inferior a 18 años, escribe: "Es menor de edad."

# SINTAXIS PARA RESOLVER EL EJERCICIO:
# Si    parametro1      es mayor o igual que    17
# if    $1              greater or equals than  17
# if    [ $1                -gt          	17 ]              
# then/entonces
#   echo ...
# else
#   echo ...
# fi

if [ $1 -ge 18 ]
then
    echo "Es mayor de edad."
else
    echo "Es menor de edad."
fi
