#!/bin/bash

# Programa al que se le pasa como parámetro una edad:
## - Si es mayor o igual a 18 años, escribe: "Está jubilado."
## - Si la edad es inferior a 18 años, escribe: "Es menor de edad."
## - Si la edad es superior a 18 años pero inferior a 67, escribe: "Es mayor de edad."

if [ $1 -ge 67 ]
then
    echo "Está jubilado."

elif [ $1 -ge 18 ]
then
    echo "Es mayor de edad."

else
    echo "Es menor de edad."
fi
